DataTorrent/docs

docs/ApexPackage.md

It is fixing many wrong blocking issues.

Adding a space before three quotes

---

docs/apex_development_setup.md

Fixed several formatting glitches.

Fix formatting issues

---

docs/configuration.md

Fixing a typo: Changed Performance turning to performance tuning

Typo fix for performance tuning 

---

docs/dtgateway_security.md

Documentation for active directory authentication, general edits and improvements, SPOI-7666 #resolve

---

docs/dtgateway_security.md

New topics like active directory were not appearing on sidebar. Fixed it. @sashadt  please review

Changes for new topics to appear correctly in sidebar

---

docs/dtgateway_security.md

SPOI-7820 Added port for Jetty module specification

---

docs/troubleshooting.md

@amberarrow  @davidyan74  Pls review the serialization considerations section I have added.

SPOI-8750   Document serialization issues and troubleshooting steps

---

docs/troubleshooting.md

"hadoop" typos corrected to "Hadoop"

Correct typos

---

docs/apex.md

Remove "incubating" from description and URL

Remove "incubating"

---

docs/troubleshooting.md

@amberarrow  I just noticed this so I thought of fixing it... can be merged?

remove incubating from all references to Apex

---

docs/app-templates/database-to-hdfs.md
docs/app-templates/hdfs-line-copy.md
docs/app-templates/hdfs-sync.md
docs/app-templates/hdfs-to-kafka-sync.md
docs/app-templates/kafka-to-hdfs-sync.md
docs/app-templates/s3-to-hdfs-sync.md

@ashwinchandrap Made numerous fixes; please take a look.

Fix typos, awkward prose, etc.

---

mkdocs.yml

Remove link to demo_videos.md since the videos don't yet exist.
@ashwinchandrap Please merge

SPOI-9784 Remove link to demo_videos.md

---

.gitignore
docs/dtgateway_api.md

@PramodSSImmaneni please review

Add authentication configuration web services spc to gateway REST api doc. SPOI-8996.

---

docs/dtgateway.md
docs/dtgateway_systemalerts.md

@amberarrow @wvary can you please review. Previously i raised pull request against wrong branch. I corrected it & raised a pull request.

Document DT Gateway System Alerts. #resolve SPOI-9972

---

docs/beginner.md

Revise buffer server and stream descriptions to be more accurate.
@vrozov @PramodSSImmaneni Please take a look

SPOI-10105 Revise description of buffer server and streams

---

docs/application_development.md
docs/beginner.md
docs/dtgateway_security.md
docs/dtmanage.md
docs/operator_development.md
docs/operators/kafkaInputOperator.md
docs/troubleshooting.md

Removed outdated information and fix typos

[SPOI-10589] Fix outdated docs

---

docs/dtgateway.md
docs/dtgateway_systemalerts.md
mkdocs.yml

@priteshm @wvary @sashadt Please review and merge.
I had to create a new item called "Alerts" in mkdocs.yml, without it, the embedded link in dtgateway.md was giving me a 404.

SPOI-10301 Revisions to improve readability

---

docs/dtgateway_security.md
docs/dtgateway_systemalerts.md

@amberarrow  pls review and merge. Also @wvary to review and comment

SPOI-11028 update the systemalerts and security documents for SMTP configuration and keystore related content

---

docs/dtgateway_api.md

Adding operator name and id to container info.

---

mkdocs.yml

menu item renamed

---

docs/dtgateway_api.md

Updated description of the following REST APIs:
POST /ws/v2/licenses
GET /ws/v2/licenses/current
Added description of the following REST APIs:
PUT /ws/v2/systemAlerts/templates/system/"{name}"
DELETE /ws/v2/systemAlerts/templates/system/'{name}"
GET /ws/v2/systemAlerts/templates/system
GET /ws/v2/systemAlerts/templates/system/"{name}"
PUT /ws/v2/systemAlerts/"validate/script"
@wvary @sashadt Could you please review the API description updates
@wvary Could you please add the template structure to the doc?

SPOI-11226 Document REST API changes for 3.8 release

---

docs/app-templates/0.10.0/database-to-database-sync.md
docs/app-templates/0.10.0/hdfs-part-file-copy.md
docs/app-templates/0.10.0/hdfs-to-hdfs-filter-transform.md
docs/app-templates/0.10.0/kafka-to-cassandra-filter-transform.md
docs/app-templates/0.10.0/kafka-to-database-sync.md
docs/app-templates/0.10.0/kafka-to-hdfs-filter-transform.md
docs/app-templates/0.10.0/kafka-to-kafka-filter-transform.md
docs/app-templates/0.10.0/kinesis-to-redshift.md
docs/app-templates/0.10.0/kinesis-to-s3.md
docs/app-templates/0.10.0/s3-to-hdfs-sync.md
docs/app-templates/0.10.0/s3-to-redshift.md

Updated README links from walkthrough

SPOI-12043-walkthrough-docs

---

docs/release_notes.md

Relnotes 3.9 heading updates

---

docs/app-templates/0.10.0/hdfs-part-file-copy.md
docs/app-templates/0.10.0/kafka-to-cassandra-filter-transform.md
docs/app-templates/0.10.0/kafka-to-kafka-filter-transform.md
docs/app-templates/hdfs-to-s3-sync.md
docs/app-templates/kafka-to-hdfs-filter.md
mkdocs.yml

@yogidevendra Please review and merge.

SPOI-11875 Fixed the links and descriptions in README files

---

docs/troubleshooting.md

Removed instances of community edition from the Troubleshooting chapter.

SPOI-12247 Update troubleshooting.md

---

docs/aws_emr_manual.md

@yatindatatorrent @daemon12 Kindly verify the changes and merge.

SPOI-12698 Update aws_emr_manual.md

---

docs/apex_development_setup.md
docs/app-templates/database-to-database-sync.md
docs/app-templates/database-to-hdfs.md
docs/app-templates/hdfs-line-copy.md
docs/app-templates/hdfs-sync.md
docs/app-templates/kafka-to-database-sync.md
docs/app-templates/kafka-to-hdfs-filter.md
docs/app-templates/kafka-to-hdfs-sync.md
docs/app-templates/s3-to-hdfs-sync.md
docs/beginner.md
docs/troubleshooting.md
docs/tutorials/topnwords-c3.md
docs/tutorials/topnwords.md

SPOI-12447 (Removing stale editions)

---

docs/dtgateway_systemalerts.md

Update the docs to reflect the new user scoped alerts

---

docs/operators/kafkaInputOperator.md

@venkateshkottapalli 
updated the KafkaInput operator document for using Kafka operators in a kerberised cluster. 
Please verify.

SPOI-13000 Document Kerberised Kafka Operator

---

docs/installation.md

@sandeshh 
Added a section in the Installation for Disaster Recovery and the steps required. 
Please verify to close this defect SPOI-12993

SPOI-12993 Disaster recovery setup

---

docs/troubleshooting.md

@chinmaykolhatkar 
Please verify. Will merge after you confirm.

Add OAS section and content

---

docs/troubleshooting.md

PR to address comments in the prev PR by @vrozov

SPOI-8750 incorporate further review comments

---

docs/menu.css

Improve nav indent and colors

---

docs/release_notes.md

Makes these headers not show up in sidenav.

Fix Release Notes 3.10 headers

---

docs/quickstartlaunchfpa.md

re-ordering steps quickstart launch FPA

re-ordering steps Quickstart Launch FPA

---

docs/troubleshooting.md

This section needs to be revisited to remove redundant content or to add new content. 
Currently corrected the heading levels and nesting common topics in the appropriate headings.

Enhance Troubleshooting section 
